// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdljzbkczhyykhzyillj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkbGp6Ymtjemh5eWtoenlpbGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NTY5MzEsImV4cCI6MjA2MTAzMjkzMX0.urlh_YAUvhu64I8ynJRGtdAUTtFURGcTn_vVAgbREAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);